### ISSUE TITLE
socket hang up on running ' wt create <filename>'

### ISSUE THREAD

**Issue by nikhil-kartha** [auth0/wt-cli#116]
$wt create <filename>
Uncaught error:  socket hang up
Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at TLSSocket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Please report this at: https://github.com/auth0/wt-cli/issues

**Comment by ggoodman** [comment]
@nikhil-kartha can you please provide a few more details:

```
wt --version
node --version
```

Can you also show the exact command you were running?

**Comment by nikhil-kartha** [comment]
$wt create refresh-token.js
...
$ wt --version
5.1.2
$ node --version
v7.8.0

**Comment by briansantura** [comment]
Also getting this error when running the "Getting Started" example. 

`echo "module.exports = function(cb) { cb(null, 'hello world'); }" > foo.js`

`wt create foo.js  `

Wt vesion, and node version.

`wt --version`
5.1.3
`node --version`
v6.10.2

**Comment by briansantura** [comment]
@nikhil-kartha Try re-installing with the `npm install wt-cli -g` command. Was able to successfully create a Webtask after doing so. 

![image](https://cloud.githubusercontent.com/assets/23461819/24929580/4c391b6a-1ebb-11e7-9e38-0437a29caa98.png)

**Comment by nikhil-kartha** [comment]
Its working for me today, without a re-installation.

Nikhil.
