### ISSUE TITLE
wt init should be in sync with "verification code" ttl

### ISSUE THREAD

**Issue by woloski** [auth0/wt-cli#12]
If more than X minutes passed (where X=verification code ttl) we should automatically re-send a verification code

```
Verification code: 
Verification must expired at this point. We re-sent a new one. (in red)
Verification code: ...
```

feedback by @cristiandouce

**Comment by woloski** [comment]
@bananaoomarang can you implement this one?

**Comment by woloski** [comment]
Actually, let's kill the process instead of re-send. It'll be easier and less error prone.

**Comment by bananaoomarang** [comment]
Don't know when the verification code expires ATM (if it does), I think it's in a webtask. Will just quit after five minutes.

**Comment by cristiandouce** [comment]
My code expired in less that 2 minutes btw.
