### ISSUE TITLE
continuous deployment from gitlab

### ISSUE THREAD

**Issue by rohit-ravikoti** [auth0/wt-cli#124]
Hi!
Is it possible to deploy from a continuous integration service like GitlabCI? How would we init the wt-cli and provide credentials?

**Comment by NotMyself** [comment]
Hi @rohit-ravikoti,

Sorry for the late response. It is possible to deploy from a CI service using the wt-cli given you can install it and store your profile values as environment variables. The process would look something like this:

1. Store URL, Container and Token values as Environment Variables with your CI provider.
    - You can get these values using this command, `wt profile ls --show-token`
1. In the prebuild step for your CI provider, install the wt cli.
    - The command would look something like `npm install wt-cli -g`
1. Also in the prebuild step, initalize the wt cli using the init command.
    - The command would look like this `wt init -p ci --url $URL --container $CONTAINER --token $TOKEN`
1. Run your normal build process.
1. Deploy your webtasks using `wt create file.js -p ci`.

Let me know if you have any clarifying questions. I am going to close this issue as it is very old and chances are you are already moved on. Feel free to reopen with current information to continue the conversation.
