### ISSUE TITLE
Special characters are not recognized in wt name unless they are url encoded

### ISSUE THREAD

**Issue by Vitouuu** [auth0/wt-cli#130]
I created a webtask from a URL with a parameter, but then I couldn't deleted unless I url encoded the special characters.
The rm command even replied with the same name but as non-matching webtask name.

This finally worked:
`wt rm task%3Fwithparams`

![screen shot 2017-05-17 at 5 23 21 pm](https://cloud.githubusercontent.com/assets/3942402/26175872/8f544236-3b2a-11e7-9e46-c95a50cef6e9.png)

**Comment by Korrd** [comment]
Maybe it would be a good idea for those commands that deal with the task name to do some urlencoding on the taskname beforehand, or to add clarification on the help screen so the user knows it should be urlencoded if special characters are used?

**Comment by Vitouuu** [comment]
It's not well handled on the web editor either; actually it cannot be opened.

![screen shot 2017-05-17 at 6 33 35 pm](https://cloud.githubusercontent.com/assets/3942402/26177313/87cb0b30-3b2f-11e7-8856-7393a55c0bec.png)

**Comment by NotMyself** [comment]
Hi @Vitouuu,

Sorry for the extremely late reply. I took a look at the current version of both the CLI and the Editor and it looks like this issue has been handled. You cannot create a task with an invalid name anymore.

![screen shot 2018-07-10 at 2 57 38 pm](https://user-images.githubusercontent.com/73120/42540048-db1e2d5a-8451-11e8-9bd1-c8a040aa3556.png)

![screen shot 2018-07-10 at 2 57 53 pm](https://user-images.githubusercontent.com/73120/42540051-de042380-8451-11e8-86fd-233f4348a7af.png)


I am going to close this ticket. Feel free to respond and reopen it if you still have questions.
