### ISSUE TITLE
wt create --bundle --ignore-package-json throws error when package.json contains no dependencies

### ISSUE THREAD

**Issue by toboid** [auth0/wt-cli#134]
If you try to create a bundled webtask that has a package.json with no dependencies and you use the `--ignore-package-json` flag, the command fails.

I have created an example [here](https://github.com/toboid/wt-cli/tree/webtask-no-deps/sample-webtasks/bundled-webtask-no-deps). When created with command `wt create --bundle --ignore-package-json .` the cli throws the following error:

```
Uncaught error:  Cannot read property 'then' of undefined
```

I was using `--ignore-package-json` in order to work around #133. The combination of these 2 issues means that it's not currently possible to create a bundled webtask that has no module dependencies

**Comment by toboid** [comment]
If you'll take a PR then i'd be very happy to look into this and submit one

**Comment by ggoodman** [comment]
Hello @toboid, I'd be happy to take you up on your offer of a PR.

As for #133, this is a bit more involved and would likely be solved in [webtask-bundle](https://github.com/auth0/webtask-bundle).

**Comment by toboid** [comment]
@ggoodman thanks, submitted
