### ISSUE TITLE
Imported sub-modules included in bundle

### ISSUE THREAD

**Issue by toboid** [auth0/wt-cli#135]
If a construct such as `import ReactDOMServer from 'react-dom/server'` is used in a bundled webtask the required module is inlined in the module, as well as installed in the container. In the case of `react-dom/server` this causes the create command to fail with 
`Uncaught error:  Request body size exceeds 122880`.

I've tested with `import map from 'lodash/map'` too and observed the same behaviour though obviously that's much easier to work around.

I have created an example of the issue [here](https://github.com/toboid/wt-cli/tree/bundle/sample-webtasks/big-bundled-webtask).

**Comment by NotMyself** [comment]
Hi @toboid,

Thanks for reaching out to us and the excellent test case. We have fixed the issue. You simply need to update to the latest version of the wt-cli: `npm update -g wt-cli`
