### ISSUE TITLE
Profile creation hangs when using Node.js v8.x.x

### ISSUE THREAD

**Issue by mauricioschneider** [auth0/wt-cli#137]
Reproduction steps:

- Begin initialization of new profile with `wt-cli init --profile 'new-profile'`
- Input your email
- When prompted for the verification code, the cursor won't respond to typing
- At this point, it's not possible to stop the process using `ctrl+c`

**Comment by kotarac** [comment]
Seems like a issue with node which was fixed with PR nodejs/node#13560.
New version of node with the fix should be released soon.

**Comment by kotarac** [comment]
@mauricioschneider should be fixed with node 8.1.1

**Comment by mauricioschneider** [comment]
@kotarac Thanks for letting me know! Will give it a try and close the issue if solved.

**Comment by mauricioschneider** [comment]
Can confirm node v8.1.1 fixes the issue, thanks @kotarac
