### ISSUE TITLE
Mention 'secrets' in the cron docs

### ISSUE THREAD

**Issue by joeyespo** [auth0/wt-cli#140]
I recently used the CLI to create a cron job. It had a secret associated with it.

I noticed that you can add secrets to cron jobs in the editor, so I tried running `wt cron schedule --secret KEY=VALUE` and that worked. The problem is that I didn't know it was possible until trying it since [the docs don't mention it](https://webtask.io/docs/cron).

Or, if `--secret` isn't intended to be used here, it might be worth mentioning that instead.

Btw, webtask.io is awesome 😃

**Comment by rwtombaugh** [comment]
We are in the process of re-writing all of the documentation around webtasks and Extend, so we'll be sure to include this in the new version
