### ISSUE TITLE
Saw `ReferenceError: regeneratorRuntime is not defined` when using async / await

### ISSUE THREAD

**Issue by joeyespo** [auth0/wt-cli#141]
I read that adding `"use latest"` to your script would run the code through Babel, so I embraced modern JS from the get-go on a recent project. Really cool!

However, after deploying I saw `ReferenceError: regeneratorRuntime is not defined` error from using async / await. So instead of relying on the builtin Babel support, I ran it through Babel locally [to test](https://github.com/auth0/wt-cli/issues/139) and deploy the result. Note that I'm not using `--bundle` since it's a simple script.

Looks like [it's missing the regenerator runtime](https://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined-with-async-await). I ended up working around this by running `babel` locally on my source and deploying that instead. Here's my `.babelrc` file:

```json
{
  "presets": ["env"],
   "plugins": [
    ["transform-runtime", {
      "polyfill": false,
      "regenerator": true
    }]
  ]
}
```

**Comment by gaastonsr** [comment]
Thanks so much!

**Comment by NotMyself** [comment]
Hi Everyone,

Webtask.io now runs on Node 8 directly. Async/Away is supported. I am going to close this issue. Feel free to respond and reopen if you have any questions.
