### ISSUE TITLE
rejecting new cron job due to max cron jobs per container limit

### ISSUE THREAD

**Issue by baskin** [auth0/wt-cli#142]
Got following on trying to add a new cron.
Couldn't find any information on limit on number of crons in the documentation. Can you pl help clarify?

```
wt cron schedule '50 * * * *' xxx --meta source=source --meta app=appname --name yyy
Uncaught error:  rejecting new cron job due to max cron jobs per container limit
Error: Bad Gateway
    at Request.callback (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:675:11)
    at /usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:883:18
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/parsers/json.js:16:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by baskin** [comment]
Can you please help me understand -- how is a container associated with a cron? Sorry, couldn't find in the documentation.

**Comment by ggoodman** [comment]
Hello @baskin, we have a limit of 10 cron jobs per webtask.io account. Can you tell us more about how you are using so many cron jobs?

**Comment by baskin** [comment]
@ggoodman, I have:
- a webtask that fetches news articles from a news source. The news source is an input to the webtask.
- one cron for each news source, that runs once every hour.
- there are a total of ~30 news sources and hence ~30 crons.

If 10 is a hard limit, i can do it differently, e.g. by keeping a single cron that runs 30 times an hour, and figuring out which news source to trigger it for though some other logic.

It there a limit on the execution rate of crons. Are these limits documented somewhere?

Thanks,

**Comment by baskin** [comment]
Hi Team, @ggoodman,

I collapsed into a single cron - but am now getting 

```
body:              {
  "code": 400,
  "error": "Script exceeds the size limit.",
  "message": "Script exceeds the size limit of 102400.",
  "error_source": "sandbox"
}

```

However, the job runs if i execute it via the panel.
Also checked the size of the script way below the state limit (of 100KB).

What could be wrong? Kindly help.

**Comment by baskin** [comment]
Ok then.

For some reason by using the `function(ctx, req, res)` signature, I no longer get the issue.
I'm closing the ticket. Though it would be great it someone could answer why this is working now.

**Comment by ggoodman** [comment]
@baskin we've deployed a change to the platform that should address this unexpected behaviour. Please let us know if this clears things up for you.
