### ISSUE TITLE
add support for moment plugins

### ISSUE THREAD

**Issue by gwmccull** [auth0/wt-cli#148]
I'm trying to create a cron task that uses `moment` and `moment-recur`.

The recommended usage for `moment-recur` is:

```
const moment = require('moment');
require('moment-recur');
moment().recur()...
```

However, when I try to do that in a webtask, I get this error:

```
{
  "code": 400,
  "error": "Script returned an error.",
  "details": "Unknown error.TypeError: moment(...).recur is not a function"
}
```

When I scheduled this cron task, I had the adjacent `package.json` file so it appeared to have picked up the dependencies:

```
Name:        xxxx
State:       active
Container: xxxx
Schedule:    0 0 22 * *
Next run:    9/22/2017, 12:00:00 AM
Meta.wt-node-dependencies: {"minimist":"1.2.0","moment":"2.18.1","moment-recur":"1.0.7","request":"2.81.0","request-promise-native":"1.0.4"}
```

The function call works as expected if I run it in Node.

**Comment by ggoodman** [comment]
@gwmccull this is a know issue related to node modules having peer dependencies under our approach to providing low-latency access to the npm registry. We will let you know if and when we have a solution or work-around.

**Comment by ggoodman** [comment]
Hey @gwmccull, just saw your blog post (https://mcculloughwebservices.com/2017/08/28/creating-github-issues-using-webtask/). Great stuff! Hello from an SNC (Incline, NV) alumni! BeerJS and TahoeJS sound like some pretty great excuses for a visit to the alma mater and family in Tahoe City!

**Comment by gwmccull** [comment]
@ggoodman That'd be great to meet you!  We meet on the 3rd Tuesday of every month.  Let me know if you're interested in speaking at one of the meetings.  We'd be happy to learn more about Auth0 or whatever else you're working on
