### ISSUE TITLE
Error resolving TXT DNS records for new custom domain

### ISSUE THREAD

**Issue by traderd65** [auth0/wt-cli#149]
Setup custom domain serverless-pl.us following the NameCheap/CloudFlare guide. Currently only CNAME record exists in CloudFlare (may still be propagating as it's been less than 24 hours ago).

Testing the hello-custom.js example, with the command:

wt create hello-custom.js --host serverless-pl.us

I'm getting the following error:

Uncaught error:  error resolving TXT DNS records for domain serverless-pl.us: queryTxt ENODATA serverless-pl.us

There is no TXT DNS record in the CloudFlare setup!?

**Comment by motin** [comment]
You need to add a TXT DNS record to your Cloudflare DNS settings. 

Currently there are none:
```
$ dig -t txt serverless-pl.us

; <<>> DiG 9.8.3-P1 <<>> -t txt serverless-pl.us
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8400
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;serverless-pl.us.		IN	TXT

;; AUTHORITY SECTION:
serverless-pl.us.	3600	IN	SOA	darl.ns.cloudflare.com. dns.cloudflare.com. 2025595825 10000 2400 604800 3600

;; Query time: 96 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Fri Sep  8 01:37:45 2017
;; MSG SIZE  rcvd: 96

```

**Comment by traderd65** [comment]
Thank you, will be adding the TXT DNS record manually.
