### ISSUE TITLE
Updating an Existing CRON Schedule Removes Secrets

### ISSUE THREAD

**Issue by NotMyself** [auth0/wt-cli#155]
A customer reported issue: https://auth0.zendesk.com/agent/tickets/27553

### Via CLI

1. `wt cron schedule "1 * * * *" foo.js --secret FOO=BAR`
1. `wt inspect foo --decrypt` 
  - **Note:** secrets are stored
1. `wt update foo foo.js`
1. `wt inspect foo --decrypt`
  - *Note:* secrets are maintained
1. `wt cron schedule "* * * * *" foo.js`
1. `wt inspect foo --decrypt`

## Result

The schedule has changed but the secrets have been removed.

## Expected Result

Secrets should be maintained for CRON schedule updates.

## Comments

There appears to be no way to simply update the CRON schedule via the CLI. The CRON command appears to be destructive for an existing webtask. It will clear secret, meta ect values if not supplied every time.

The editor appears to hide this from you by always supplying these values. The CLI does not which is confusing for users.

**Comment by tjanczuk** [comment]
I think the problem is in the perception around `wt cron schedule` command. This command is not an *update*, it is a complete *re-create* of the CRON job. This means secrets must be re-specified. 

The `wt update` only updates code as far as I know.

**Comment by NotMyself** [comment]
Agreed, I think this is an indication we need a `wt cron update` command.

**Comment by tjanczuk** [comment]
A cheap improvement could be to introduce `wt cron create` and deprecate `wt cron schedule`

**Comment by NotMyself** [comment]
It seems weird that there is no easy way to update a cron schedule. It is pretty easy to typo `1 * * * *` when what you really mean is `* * * * *` and there is no simple way to fix it without destroying your webtask.

**Comment by ggoodman** [comment]
What about `wt cron update [--schedule new_schedule] [--state new_state]` sub-command?

**Comment by NotMyself** [comment]
I think the pair of `wt cron create` & `wt cron update` are clear in their intention and might reduce confusion.

**Comment by ggoodman** [comment]
If we take the approach proposed by @tjanczuk here: https://github.com/auth0/wt-cli/issues/155#issuecomment-331230067, I would also change `wt cron create`'s signature to have the schedule as an option instead of a positional argument.

**Comment by NotMyself** [comment]
Verified fixed in 7.0.1
