### ISSUE TITLE
Debugging cron execution

### ISSUE THREAD

**Issue by baskin** [auth0/wt-cli#158]
Hi Team,

I have a function that I deploy as a 
- webtask
- cron

Executing the function as a webtask works and i get the correct result.

However, the cron fails every single time. The only response I get is through the scheduler stats and that simply says "Server Error", 500.
`
type:              error
statusCode:        500
body:              {"message":"Server error","statusCode":500}
`
Nothing is printed in logs either (if i open the streaming logs at the time the cron logs).

At this point I'm unable to further my debugging. Can you please help? 

-bhupi

**Comment by ggoodman** [comment]
Hello @baskin,

Can you please share some details on how you are creating the webtask and cron job? Specifically, what commands (please redact) are you executing and in what order? Please also share the version of the cli you are using `wt --version`.

**Comment by baskin** [comment]
webtask:
`wt create build/webtask/test-cdn --secrets-file secrets --name test-cdn-webtask`

cron:
`wt cron schedule "00,15,30,45 * * * *"  build/webtask/test-cdn --secrets-file secrets --meta app=nooz --name test-cdn-cron`

wt --version
`6.5.1`

**Comment by ggoodman** [comment]
Hi @baskin, when you schedule a cron job, you are actually automatically creating an underlying webtask by the same name. Please not that cron jobs created using `wt-cli` as of `6.3.0` will have the middleware compiler and cron-authentication middleware set up. This means that direct invocations of the webtask must have an `Authorization: Bearer <token>` header whose `<token>` is the webtask token that represents the cron job's webtask.

The token in question could be determined using ```bash
wt cron get test-cdn-webtask -o json | jq ".token"
```

You can omit the `| jq ".token"` if you don't have the `jq` utility available. In this case, you would need to look at the root `token` property of the json output.

**Comment by baskin** [comment]
Thanks, closing the issue.
