### ISSUE TITLE
Feature request: wt create for inline code

### ISSUE THREAD

**Issue by heymartinadams** [auth0/wt-cli#167]
Hi Webtask team,

Feature request: if code is a single line, allow `wt create` for an inline code, like this:

```
wt create "module.exports = (context, callback) => require('some-package')(context, callback)"  --name MyWebtask  --secret privateKey='__PRIVATE_KEY__' --parse-body --meta wt-node-dependencies='{\"some-package\":\"1.0.0\"}'
```

In this case, most of the code is executed via an npm package, so the actual webtask code is short.

**Comment by NotMyself** [comment]
Hi @heymartinadams,

Thanks for the feedback. We will not be adding this functionality in the near future. I have added it to a list of feature requests to be evaluated in the future.
