### ISSUE TITLE
Is it possible to set NODE_ENV to production

### ISSUE THREAD

**Issue by dbismut** [auth0/wt-cli#172]
Hi - I was wondering if it was possible to set NODE_ENV to production? Currently it's set to `webtask`, but Express requires that it's set to `production` for optimisation and also to avoid showing stack trace in error. I think this is critical. Thanks!

**Comment by NotMyself** [comment]
Hi @dbismut,

Sorry for the very late reply on this issue. I am working to try to get all of the old issues cleaned up.

Webtask is fairly unique in that we need to support both local and editor based development workflows. The NODE_ENV being set to `webtask` supports the editor based flow.

I think the simplest approach for you is to add a small block to the top of your production webtask like this:

```javascript
if (process.env.NODE_ENV === 'webtask') {
  process.env.NODE_ENV = 'production';
}
```
