### ISSUE TITLE
Does --prod really work?

### ISSUE THREAD

**Issue by karllhughes** [auth0/wt-cli#177]
In the documentation [here](https://webtask.io/docs/wt-cli) the flag is mentioned as working: `Use --prod to allow the webtask server to cache the webtask's code between runs.`

But in the CLI, when I run `wt create -h` I see that it is deprecated: 

```
--prod                Deprecated and ignored
```

So does this flag really work? If not, is there a way to tell Webtask via the CLI that the task may be cached? Thanks!

**Comment by NotMyself** [comment]
Hi @karllhughes, Sorry for the late reply. I am attempting to clean up these old issues on our repositories. The --prod flag is no longer used at all and will be ignored. Tasks are now automatically cached for the lifecycle of the webtask container.

I have updated the documentation and it should be on the site shortly.
