### ISSUE TITLE
wt create default message is confusing

### ISSUE THREAD

**Issue by woloski** [auth0/wt-cli#18]
We've got feedback from @cristiandouce and @mgonto that they are not sure what to do with the webtask url on `wt create`.

So I suggest adding something like this:

```
$ wt create foo.js
webtask succesfuly created (in green)

        $ curl https://...../foo
```

unless we are in `--watch` mode

**Comment by bananaoomarang** [comment]
We could add one in the welcome message maybe, but doing this breaks being able to curl $(wt create ...) which is irritating for scripting.

**Comment by woloski** [comment]
Yes, maybe add a new modifier raw-url?

**Comment by bananaoomarang** [comment]
We could just show a message on the first `wt create` maybe? Adding a modifier to remove a tutorial message doesn't feel quite right, but maybe I'm being overcautious.

**Comment by woloski** [comment]
yes thought about doing that but also felt hackish. But let's try that.

**Comment by bananaoomarang** [comment]
It doesn't seem ideal to me either, we'd have to save something to `~/.webtask.cfg`. I don't think it's unusual to track the first run in 'user friendly' tools though.
