### ISSUE TITLE
tighter integration with auth0

### ISSUE THREAD

**Issue by woloski** [auth0/wt-cli#19]
### authenticated webtask

```
wt create webtask.js --auth
```

This webtask will be secured so that only can be called with a valid JSON Web Token on the `Authorization` header signed with a pre-configued secret. By default we will have a shared Auth0 account for this that will have an application/client registered. 

If the Authorization header is not provided, then return 401.
### authenticated webtask based on `email`

```
wt create webtask.js --auth="@company.com,foo@gmail.com"
```

This will not only check the token is valid but also that the `email_verified` flag on the token is `true` and it matches one of these: an email with @company.com domain or an email with foo@gmail.com. A user can specify multiple emails and/or domains.
### authenticated webtask with your own Auth0 account

```
wt create webtask --auth --clientid=... ---clientsecret=...
```

With this setting you can configure your own Auth0 clientid and secret.

**Comment by darkyen** [comment]
Is there a time-estimate on this ? This makes life so much easier than having to use Amazon STS :P

**Comment by darkyen** [comment]
I am curious how did I end up unassigning @bananaoomarang  ?

**Comment by rwtombaugh** [comment]
With the move to Auth V2 with webtasks, this issue no longer applies as far as I understand it
