### ISSUE TITLE
Error installing wt-cli due to old got module restricting node version to < 7

### ISSUE THREAD

**Issue by brec-c** [auth0/wt-cli#203]
Issue summary line actually fits the whole issue.  

got@5.7.1 has a restriction on node version to >= 0.10.0 < 7.  

Hopefully updating to the latest got is safe as that version at least removes the restriction.

**Comment by rwtombaugh** [comment]
Can you provide specific repro steps? We just installed the wt-cli using node8

**Comment by brec-c** [comment]
it's pretty much just the installation step: `npm install wt-cli -g`

it must be environmental if you're not seeing the issue.  Here's the output
I'm seeing:

λ npm install wt-cli -g

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to
"coffeescript" (no hyphen)

npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at
least 2.1.6 to avoid a serious bug with socket data flow and an import
issue introduced in 2.1.0

npm ERR! code ENOTSUP

npm ERR! notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0
<7"} (current: {"node":"8.7.0","npm":"5.6.0"})

npm ERR! notsup Not compatible with your version of node/npm: got@5.7.1

npm ERR! notsup Not compatible with your version of node/npm: got@5.7.1

npm ERR! notsup Required: {"node":">=0.10.0 <7"}

npm ERR! notsup Actual:   {"npm":"5.6.0","node":"8.7.0"}


I don't understand why you're not seeing the same thing?  I must not fully
understand npm global installs?

Hope this helps.

**Comment by NotMyself** [comment]
@brec-c 

This issue should be resolved with the release of v11.0.0.
