### ISSUE TITLE
wt profile migrate does not support named/multiple profiles?

### ISSUE THREAD

**Issue by dbertram** [auth0/wt-cli#209]
Steps:

1. Add default profile: e.g. `wt init foo@example.com`
1. Add a named profile: e.g. `wt init -p myNamedProfile bar@example.com`
1. Run `wt profile -p myNamedProfile migrate`

Expected: Start migrating the specified named profile

Actual: Error message:

`wt profile: error: argument "profile_command": Invalid choice: myNamedProfile (choose from [init, ls, get, rm, nuke, migrate])`

**Comment by NotMyself** [comment]
Hello @dbertram,

The Node 8 migration is complete and the migration functionality has been removed from the CLI. I am going to close this issue.
