### ISSUE TITLE
Can't get webtask to return the proper value when using ES6

### ISSUE THREAD

**Issue by jrgleason** [auth0/wt-cli#215]
I have the following...

```
modules.export = function(ctx, done){
  done(null, {
      response: "Test"
  })
}
```

When I run I get...

> {
>   "code": 400,
>   "message": "Compilation failed: modules is not defined",
>   "error": "modules is not defined",
>   "stack": "ReferenceError: modules is not defined\n    at eval (webpack://webtask/./uportConnect.js?:16:1)\n    at Object../uportConnect.js (/data/io/1a746477-76d8-4fe7-8752-cc942f9bd1f0/webtask.js:98:1)\n    at __webpack_require__ (/data/io/1a746477-76d8-4fe7-8752-cc942f9bd1f0/webtask.js:22:30)\n    at /data/io/1a746477-76d8-4fe7-8752-cc942f9bd1f0/webtask.js:86:18\n    at Object.<anonymous> (/data/io/1a746477-76d8-4fe7-8752-cc942f9bd1f0/webtask.js:89:10)\n    at WebtaskModule.compileWebtask (/data/sandbox/lib/module.js:95:34)\n    at defaultJavascriptCompiler (/data/sandbox/lib/compiler.js:119:30)\n    at defaultCompiler (/data/sandbox/lib/compiler.js:128:16)\n    at /data/sandbox/lib/compiler.js:231:17\n    at /data/sandbox/node_modules/async/dist/async.js:3880:24"
> }

So I try to change to the ES6 version...

```
"use latest";
export default function(ctx, done){
  done(null, {
      response: "Test"
  })
}
```

When I run like this `./node_modules/.bin/wt create --bundle --watch uportConnect.js` I get the following error...

> {
>   "code": 400,
>   "message": "Invalid webtask code",
>   "error": "Supplied code must return or export a function."
> }

**Comment by SkyHacks** [comment]
Can you try replacing `modules.export` with `module.exports`?

**Comment by jrgleason** [comment]
@SkyHacks Good catch but unfortunately just a typo. I tried both...

```
module.export = function(cb){
    cb(null, "Hello World")
}
```

and

```
module.export = function(ctx, done){
  done(null, {
      response: "Test"
  })
}
```

same result...

```
[13:40:09.671Z]  INFO wt: 
    {
      "code": 400,
      "message": "Invalid webtask code",
      "error": "Supplied code must return or export a function."
    }
```

**Comment by SkyHacks** [comment]
Notice `exports` has a trailing ‘s’.

**Comment by NotMyself** [comment]
@jrgleason the pattern needs to look like this:

```javascript
module.exports = function(context, cb) {
  cb(null, { hello: context.query.name || 'Anonymous' });
};
```
