### ISSUE TITLE
Messy output for examples in help [Windows]

### ISSUE THREAD

**Issue by harriha** [auth0/wt-cli#34]
Hi,

Not sure whether this should be reported against nested-yargs instead, and not sure if this is a bug or a feature in the first place. But here it goes anyway, feel free to close this in case you don't see anything to change here.

The `wt` (or `wt --help` or equivalent) command prints out the help with examples, but is showing the full path to the executable. At least on Windows, this leads to quite messy output, making it harder to spot the essential part of each example. I'd personally be just fine with `wt create --name foo file.js` etc.

![wt-examples-output](https://cloud.githubusercontent.com/assets/101693/9745312/a8716c22-5679-11e5-904a-5b4b77df37e6.PNG)

**Comment by NotMyself** [comment]
Hello @harriha,

Thank you for reporting this issue. We will not be fixing this issue at this time. If you would like to submit a PR to resolve it, feel free to do so.
