### ISSUE TITLE
A way to see the tasks created (and how to delete them)?

### ISSUE THREAD

**Issue by harriha** [auth0/wt-cli#35]
Hi,

Just started playing around with webtasks and only trying to get my head around the architecture now, and thus might well be missing something here. But, after creating a couple of tasks, I started wondering where could I see all tasks I've created? And how about deleting them? I see a fairly full-featured CLI API for managing scheduled tasks, but how about the regular ones? 

I assume all these tasks are gone if I delete the profile or revoke my token (?).

**Comment by ggoodman** [comment]
@harriha webtasks that are not associated with a schedule are essentially stateless. What I mean by that for all intents and purposes is that the url *is* the webtask and therefore there is nothing to list or destroy. What you do with your webtask urls (and underlying tokens) is really up to you.

As for revoking tokens, that is not something that we have exposed via the cli or api yet. Can you elaborate on the use-cases you envision?

This post by @tjanczuk details some of the rationale and architecture underlying the webtask platform: https://medium.com/aws-activate-startup-blog/sandboxing-code-in-the-era-of-containers-294edb3a674

Does that help answer your questions?

**Comment by harriha** [comment]
Hi @ggoodman,

Thanks for your reply. The thing I'm wondering is that if I create a web task (= an exposed URL which runs some custom code) and would like to get rid of that (= destroy the URL to prevent people/systems who know the URL from running it), how to do that? Also, after some time, I might not remember what tasks/URLs I've created, so there's a chance of "losing" the tasks I've created but leaving them open to the world - which, in the worst case, might do something harmful for my or someone else's systems if the URLs are known by other parties. 

All in all, just would like to get exact up-to-date status of tasks (= URLs) I've created and a way to delete them. Currently, I'm feeling a bit suspicious to start adding some actual business code to web tasks since I'm not certain if I can clean them away if/when I need to. Surely, I can replace them with a dummy task, but the case where I forget what I've created still remains.

As said, not fully clear on the overall architecture yet, need to look into it when I find the time, but this was my first source of confusion, not sure if just me or if this is an actual problem :). And apologies if this discussion takes place in wrong repository/forum, not exactly (only) CLI related.

**Comment by jasonbarone** [comment]
I'm concerned about this issue as well. Since I started a Webtask account I've been creating random stuff. As of this point I have no clue what I typed during tests.

Furthermore, like @harriha said, what's most concerning is putting some sort of production task out there and quite simply forgetting about it, or changing something and not realizing there's a Webtask that can potentially still be executed.

It would be helpful to have more functionality to understand which tasks are currently associated with the account.

**Comment by tjanczuk** [comment]
We are working on adding full CRUD over named webtasks (the ones that you can access with a vanity URL) to our HTTP APIs. Until then, HTTP APIs for named webtasks only offer one endpoint /api/tokens/issue which has the upsert semantics. Given that, if you want to prevent future use of an existing webtask ("delete"), you can override it with code that does nothing. 

Stayed tuned for the full CRUD support.

**Comment by harriha** [comment]
@tjanczuk Thanks for the update, good to hear full CRUD-like support is in the works.

**Comment by ggoodman** [comment]
@harriha @jasonbarone the webtask cli and platform support enumerating and deleting named webtasks. Closing.
