### ISSUE TITLE
Impossible to init through proxy

### ISSUE THREAD

**Issue by freefire8** [auth0/wt-cli#40]
Hi, 

I've seen with the team on slack, it seems that the wt init (i'm on windows) is not reading any proxy values, preventing me to do correctly the init process with my id.

Working on windows, node 4.2.6, wt-cli 1.1.4

**Comment by dev101** [comment]
+1
doesn't work behind a proxy
![image](https://cloud.githubusercontent.com/assets/459389/16273552/bace1f46-38aa-11e6-88d4-a4804f72cbae.png)

**Comment by ggoodman** [comment]
Forward proxy support is enabled in: 02bfb1ff88f0783c6f80580b629ef68697a75301
