### ISSUE TITLE
Default CRON interval should be less frequent

### ISSUE THREAD

**Issue by tjanczuk** [auth0/wt-cli#47]
The `wt cron -h` shows `wt cron schedule [options] "* * * * *" [file_or_url]` as  hint for creating a CRON. Should we use a less frequent default (e.g. every 15 mins) since otherwise we will end up with a million of 1-minute hello, world CRON jobs?

**Comment by ggoodman** [comment]
@tjanczuk I do not see where this default interval is indicated. That hint is no longer present in `v2`.

**Comment by ggoodman** [comment]
As of 3b01a1b381fdaf36c91ca9bfbd2489b0ce641347, `wt cron schedule --help` will show the following hint at the bottom:

```
Examples:
1. Create a webtask that runs every five minutes:
  $ wt cron schedule 5m ./sample-webtasks/hello-world.js
2. Create a webtask that runs every Tuesday at 09:05:
  $ wt cron schedule "5 9 * * 2" ./sample-webtasks/hello-world.js
```

**Comment by ggoodman** [comment]
Closing given https://github.com/auth0/wt-cli/issues/47#issuecomment-189009973
