### ISSUE TITLE
Feature Request: Search directory tree for nearest .webtask config file

### ISSUE THREAD

**Issue by colllin** [auth0/wt-cli#54]
I want to share a project-specific `.webtask` file with other developers working on the project, without having to explain "First create a `.webtask` file in your home directory, then paste this in.  Or if you already have one, you should manually merge the JSON."  Not to mention if you needed to make changes to existing profiles...

I poked around in the code.  It seems like potentially the `ConfigFile` stuff could take care of this?  Can you recommend how and where you would make this addition, and maybe I can get it done?

**Comment by colllin** [comment]
Better yet, MERGE all webtask configs from all parent directories.  Or a simpler approach... just let me manually specify the config file?  `wt update whatever whatever.js --config .webtask`

**Comment by zanona** [comment]
This would be helpful indeed.
Is there any alternative for this currently besides setting env vars `--url` `--token` and `--container` individually?

**Comment by NotMyself** [comment]
Hello @colllin and @zanona,

Thank you for the feedback. Shared webtask profiles are not currently a supported workflow. We will not be fixing this issue at this time.
