### ISSUE TITLE
Add module: getstream

### ISSUE THREAD

**Issue by tjanczuk** [auth0/wt-cli#74]
https://auth0.zendesk.com/agent/tickets/12677

**Comment by jeveloper** [comment]
Thank you/Dinkue , 

Getstream is a great service, it would be amazing.

**Comment by tjanczuk** [comment]
Released in 10.4.3

**Comment by jeveloper** [comment]
Hi

What are you referring to 10.4?  (wt-cli seems to be much lower version)
I use this site to check for modules: 
https://tehsis.github.io/webtaskio-canirequire/

Its not showing "getstream" 
thanks

**Comment by tjanczuk** [comment]
10.4 .3 is our internal release number. The module is now available on webtask.it.auth0.com and can be requested with `require('getstream')`. 

The https://tehsis.github.io/webtaskio-canirequire/ at the moment does not show all the modules available. It is a bug, we will fix it shortly.

**Comment by jeveloper** [comment]
Awesome !!

**Comment by jeveloper** [comment]
One more thing, just curious, hope you'll upgrade to node 6.X , definitely faster and more compatible to ES6. I understand that current containers use 4.x, is that right?
