### ISSUE TITLE
Cannot read property 'formatUsage' of undefined

### ISSUE THREAD

**Issue by tjanczuk** [auth0/wt-cli#75]
One issue and a question.

Issue:

```
tj-mac:wt-cli tomek$ ./bin/wt token create -p int --url https://wt-is-1.it.auth0.com 
{ [Error: --token must be specified with --url] code: 'E_INVALID', data: undefined, isCli: true } 'undefined' 'undefined'
Uncaught error:  Cannot read property 'formatUsage' of undefined
```

After I comment out the line using `formatUsage`, I get the following: 

```
tj-mac:wt-cli tomek$ ./bin/wt token create -p int --url https://wt-is-1.it.auth0.com 
--token must be specified with --url
```

Question: what is rationale for this limitation? I want to take my token (opaque key in this case) from my profile, but override the url using `--url`.

**Comment by rwtombaugh** [comment]
As we move to a new authorization model, this will no longer be useful
