### ISSUE TITLE
Quickstart Step 4, "wt edit hello" doesnt execute, throws no error

### ISSUE THREAD

**Issue by idkjs** [auth0/wt-cli#81]
Step 4 on [Quickstart](https://webtask.io/cli) not working. Im on Windows 10, default browser is Firefox. I ran `wt edit hello`, `wt edit hello.js` in both Windows command prompt and Node6.5. Console logs " Opening hello in your browser...." than nothing.
![webtask-edit](https://cloud.githubusercontent.com/assets/2370391/18816461/b8918868-834a-11e6-865c-8f6045e884cf.PNG)

**Comment by jeffijoe** [comment]
Same here.

**Comment by luisrudge** [comment]
I'm also seeing this. I added a quick fix to display the url in the terminal so we can copy/paste in the browser.
