### ISSUE TITLE
The authentication webtask token cannot be used to issue new webtask tokens.

### ISSUE THREAD

**Issue by Neats29** [auth0/wt-cli#83]
I'm trying to debug a 'rule' script on the Auth0 dashboard. 

I've followed the following instructions:

```
$ echo "module.exports = function (cb) { cb(null, 'Hello'); }" > hello.js
$ wt create hello.js
```

But I'm getting the above error. Any ideas why?
Thanks

**Comment by NotMyself** [comment]
Hi @Neats29,

I am sorry for the extremely late response. Are you still having this issue? I am going to close this issue assuming you have moved on or the issue has been resolved in the last couple years. If you are still having the issue feel free to reopen the issue with current details.

Thanks!
