### ISSUE TITLE
How to use wt serve

### ISSUE THREAD

**Issue by openhoat** [auth0/wt-cli#97]
May be I missed something, but I cannot find a way to use "wt serve" command :

sample webtask "bar.js" : 
```
const webtaskTools = require('webtask-tools')
const express = require('express')
const app = express()

app.get('/', (req, res) => {
    res.json({foo: 'bar'})
})

module.exports = webtaskTools.fromExpress(app)
```
then I run :
```
$ npm i
$ wt serve ./bar.js
Your webtask is now listening for IPv4 traffic on 0.0.0.0:8080
```
then :
```
$ curl http://localhost:8080/bar
```
failed with :
```
{
  "code": 500,
  "error": "Script generated an unhandled synchronous exception.",
  "details": "TypeError: Cannot read property 'replace' of undefined",
  "name": "TypeError",
  "message": "Cannot read property 'replace' of undefined"
}
```
node version : v7.2.1

**Comment by ggoodman** [comment]
@openhoat thanks for the detailed issue. To support running unpatched express on webtask with intuitive routing (`/` in your case), we need to do some path fiddling. I suspect that we've missed some corner case that you're currently experiencing.

I will take a look.

**Comment by ggoodman** [comment]
@openhoat I believe that we have fixed this issue in recent versions of `wt-cli`. Please let me know if you are still experiencing this issue.
